# Generated by Django 2.1.1 on 2018-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='fullImage',
            field=models.URLField(verbose_name='Obrázek 4312x2868'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='image',
            field=models.URLField(verbose_name='Obrázek 752x482'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='infocard',
            field=models.URLField(blank=True, default='', verbose_name='Infokarta'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Zeměpisná šířka'),
        ),
    ]
